name: github

on:
  workflow_dispatch:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
    paths-ignore:
      - 'docs/**'
      - '*.md'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.0'

      - name: Cross-Platform build
        run: |
          make platfrom-build

      - name: Generate Changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make changelog

      - name: Release to GitHub
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker://antonyurchenko/git-release:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHANGELOG_FILE: "none"
          ALLOW_EMPTY_CHANGELOG: "true"
          DRAFT_RELEASE: "true"
        with:
          args: |
            .bin/*
